modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]] 
modId="advisor" 
version="${file.jarVersion}"
displayName="Advisor"
authors="DivineAspect,SkySom"
description='''
'''

[[dependencies.advisor]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.advisor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
